In [39]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder,StandardScaler,OneHotEncoder

In [40]:
import pickle

In [41]:
df = pd.read_csv('weatherAUS.csv')

In [42]:
df

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,No
145456,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,No
145457,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,No
145458,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,2017-06-25,Uluru,14.9,NaN,0.0,NaN,NaN,NaN,NaN,ESE,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,NaN

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  object
 1   Location       145460 non-null  object
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object
 10  WindDir3pm     141232 non-null  object
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  object
 22  RainTomorrow   142193 non-null  object
dtypes: float64(16), object(7)
memory usage: 25.5+ MB

In [44]:
df.isnull().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [45]:
df=df.dropna(subset=['RainTomorrow'])

In [46]:
df.isna().sum()

Date                 0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
Evaporation      60843
Sunshine         67816
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Cloud9am         53657
Cloud3pm         57094
Temp9am            904
Temp3pm           2726
RainToday         1406
RainTomorrow         0
dtype: int64

In [47]:
df['RainTomorrow'].value_counts()

RainTomorrow
No     110316
Yes     31877
Name: count, dtype: int64

In [48]:
x = df.drop(columns=['Date','RainToday','RainTomorrow'],axis=1)
y = df['RainTomorrow']

In [49]:
x.shape

(142193, 20)

In [50]:
le = LabelEncoder()

In [51]:
x['Location'] = le.fit_transform(x['Location'])

In [52]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.25,random_state=42)

In [53]:
x_train

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
105663,48,14.9,30.3,0.0,7.4,10.9,S,33.0,ESE,SW,15.0,11.0,19.0,12.0,1021.1,1017.8,1.0,1.0,22.2,29.7
113689,46,14.6,21.5,0.2,NaN,NaN,SSE,46.0,S,SSE,26.0,28.0,65.0,57.0,1012.6,1013.5,NaN,NaN,17.5,18.6
126081,36,9.0,23.7,0.0,NaN,NaN,W,28.0,WNW,W,11.0,15.0,59.0,45.0,NaN,NaN,NaN,NaN,14.6,23.1
110347,1,15.3,24.0,0.0,8.2,12.1,NaN,NaN,SSW,SSW,4.0,15.0,63.0,82.0,1018.1,1016.7,3.0,3.0,21.8,21.8
72477,20,17.3,37.5,0.0,8.6,11.4,N,39.0,NE,NW,9.0,15.0,26.0,12.0,1009.6,1006.2,7.0,4.0,23.8,35.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112920,46,9.0,18.9,12.6,NaN,NaN,W,43.0,WNW,W,20.0,15.0,NaN,NaN,1017.5,1017.7,NaN,NaN,15.8,17.6
122810,31,13.1,19.9,3.0,1.2,2.3,SW,39.0,SW,W,2.0,13.0,90.0,55.0,1018.1,1018.2,7.0,7.0,15.4,19.1
106280,48,10.8,25.5,0.0,12.0,13.0,SSW,44.0,SSW,SSE,26.0,15.0,41.0,21.0,1015.7,1012.6,0.0,0.0,15.3,23.1
135107,17,11.3,21.4,0.0,NaN,NaN,ESE,39.0,SSE,SE,19.0,22.0,75.0,79.0,NaN,NaN,8.0,4.0,15.8,15.7
124925,36,10.3,28.1,0.0,NaN,NaN,SSE,46.0,NE,ESE,15.0,13.0,51.0,28.0,NaN,NaN,NaN,NaN,19.7,26.7

In [54]:
cat = x.select_dtypes(include='object').columns
num = x.select_dtypes(exclude='object').columns

In [55]:
from sklearn.pipeline import Pipeline

In [56]:
numerical_pipeline = Pipeline([
    ('imputer_numerical',SimpleImputer(strategy='median')),
    ('sclaer',StandardScaler())
])
catogorical_pipeline = Pipeline([
    ('catogorical_imputer',SimpleImputer(strategy='most_frequent')),
    ('one_hot_encoder',OneHotEncoder(drop='first',handle_unknown='ignore',sparse_output=False))
])

In [57]:
transformer = ColumnTransformer([
    ('numeric_transformer',numerical_pipeline,num),
    ('categorical_transformer',catogorical_pipeline,cat)
])

In [58]:
x_train=transformer.fit_transform(x_train)
x_test = transformer.transform(x_test)

In [59]:
with open('LabelEncoder.pkl','wb') as file:

    pickle.dump(le,file)

In [60]:
with open('preprocessor.pkl','wb') as ohe:
    pickle.dump(transformer,ohe)

In [61]:
x_train.dtype

dtype('float64')

In [62]:
import tensorflow as tf

In [63]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import datetime

In [64]:
x_test.dtype

dtype('float64')

In [65]:
models = Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(18,activation='relu'),
    Dense(8,activation='sigmoid'),
    Dense(1,activation='sigmoid')
])

c:\Users\maith\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [66]:
models.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ (None, 64)             │         4,032 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 18)             │           594 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 8)              │           152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,867 (26.82 KB)

 Trainable params: 6,867 (26.82 KB)

 Non-trainable params: 0 (0.00 B)

In [67]:
models.compile(optimizer='Adam',loss='BinaryCrossentropy',metrics=['accuracy'])

In [68]:
logdir = 'logs/fits/'+datetime.datetime.now().strftime('%Y-%M-%d-%H-%M_%S')

In [69]:
tenser_flow_claaback = TensorBoard(logdir,histogram_freq=1)

In [70]:
EarlyStopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [71]:
lee = LabelEncoder()
y_train = lee.fit_transform(y_train)
y_test = lee.transform(y_test)

In [72]:
weights = {0: 1.0, 1: 3.0}

In [73]:
history = models.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=100,
                     callbacks=[tenser_flow_claaback,EarlyStopping_callback],class_weight=weights)

Epoch 1/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.7942 - loss: 0.6929 - val_accuracy: 0.8078 - val_loss: 0.4331
Epoch 2/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8123 - loss: 0.6385 - val_accuracy: 0.8026 - val_loss: 0.4449
Epoch 3/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8144 - loss: 0.6247 - val_accuracy: 0.8161 - val_loss: 0.4086
Epoch 4/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8152 - loss: 0.6159 - val_accuracy: 0.8210 - val_loss: 0.4023
Epoch 5/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - accuracy: 0.8167 - loss: 0.6092 - val_accuracy: 0.8166 - val_loss: 0.4099
Epoch 6/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - accuracy: 0.8181 - loss: 0.6032 - val_accuracy: 0.8115 - val_loss: 0.4169
Epoch 7/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - accuracy: 0.8191 - loss: 0.5973 - val_accuracy: 0.8138 - val_loss: 0.4093
Epoch 8/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8188 - loss: 0.5928 - val_accuracy: 0.7919 - val_loss: 0.4335
Epoch 9/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - accuracy: 0.8194 - loss: 0.5879 - val_accuracy: 0.8266 - val_loss: 0.3857
Epoch 10/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8221 - loss: 0.5831 - val_accuracy: 0.8071 - val_loss: 0.4123
Epoch 11/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8224 - loss: 0.5790 - val_accuracy: 0.7953 - val_loss: 0.4289
Epoch 12/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8227 - loss: 0.5753 - val_accuracy: 0.7914 - val_loss: 0.4397
Epoch 13/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8224 - loss: 0.5717 - val_accuracy: 0.8219 - val_loss: 0.3984
Epoch 14/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8244 - loss: 0.5687 - val_accuracy: 0.8291 - val_loss: 0.3790
Epoch 15/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8241 - loss: 0.5652 - val_accuracy: 0.8062 - val_loss: 0.4145
Epoch 16/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8238 - loss: 0.5617 - val_accuracy: 0.8308 - val_loss: 0.3770
Epoch 17/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8248 - loss: 0.5596 - val_accuracy: 0.8134 - val_loss: 0.4015
Epoch 18/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8253 - loss: 0.5560 - val_accuracy: 0.8025 - val_loss: 0.4250
Epoch 19/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8251 - loss: 0.5535 - val_accuracy: 0.8088 - val_loss: 0.4098
Epoch 20/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - accuracy: 0.8256 - loss: 0.5508 - val_accuracy: 0.8192 - val_loss: 0.3988
Epoch 21/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8261 - loss: 0.5481 - val_accuracy: 0.8220 - val_loss: 0.3859
Epoch 22/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8272 - loss: 0.5447 - val_accuracy: 0.7922 - val_loss: 0.4309
Epoch 23/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8273 - loss: 0.5427 - val_accuracy: 0.8029 - val_loss: 0.4144
Epoch 24/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8270 - loss: 0.5405 - val_accuracy: 0.7884 - val_loss: 0.4292
Epoch 25/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8263 - loss: 0.5383 - val_accuracy: 0.7990 - val_loss: 0.4254
Epoch 26/100
3333/3333 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8284 - loss: 0.5366 - val_accuracy: 0.7862 - val_loss: 0.4297

In [74]:
models.save('newgen.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [75]:
## load TenserBoard extenson
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [76]:
%tensorboard --logdir logs

Reusing TensorBoard on port 6006 (pid 1696), started 0:26:14 ago. (Use '!kill 1696' to kill it.)